# Form implementation generated from reading ui file 'nutrient_ratio_editor.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_nutrient_ratio_editor(object):
    def setupUi(self, nutrient_ratio_editor):
        nutrient_ratio_editor.setObjectName("nutrient_ratio_editor")
        nutrient_ratio_editor.resize(687, 50)
        self.horizontalLayout = QtWidgets.QHBoxLayout(nutrient_ratio_editor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_nutrient_name = QtWidgets.QLabel(nutrient_ratio_editor)
        self.lbl_nutrient_name.setObjectName("lbl_nutrient_name")
        self.horizontalLayout.addWidget(self.lbl_nutrient_name)
        self.txt_nutrient_mass = QtWidgets.QLineEdit(nutrient_ratio_editor)
        self.txt_nutrient_mass.setObjectName("txt_nutrient_mass")
        self.horizontalLayout.addWidget(self.txt_nutrient_mass)
        self.cmb_nutrient_mass_unit = QtWidgets.QComboBox(nutrient_ratio_editor)
        self.cmb_nutrient_mass_unit.setObjectName("cmb_nutrient_mass_unit")
        self.horizontalLayout.addWidget(self.cmb_nutrient_mass_unit)
        self.label_2 = QtWidgets.QLabel(nutrient_ratio_editor)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txt_ingredient_mass = QtWidgets.QLineEdit(nutrient_ratio_editor)
        self.txt_ingredient_mass.setObjectName("txt_ingredient_mass")
        self.horizontalLayout.addWidget(self.txt_ingredient_mass)
        self.cmb_ingredient_mass_unit = QtWidgets.QComboBox(nutrient_ratio_editor)
        self.cmb_ingredient_mass_unit.setObjectName("cmb_ingredient_mass_unit")
        self.horizontalLayout.addWidget(self.cmb_ingredient_mass_unit)

        self.retranslateUi(nutrient_ratio_editor)
        QtCore.QMetaObject.connectSlotsByName(nutrient_ratio_editor)

    def retranslateUi(self, nutrient_ratio_editor):
        _translate = QtCore.QCoreApplication.translate
        nutrient_ratio_editor.setWindowTitle(_translate("nutrient_ratio_editor", "Form"))
        self.lbl_nutrient_name.setText(_translate("nutrient_ratio_editor", "nutrient_name: "))
        self.label_2.setText(_translate("nutrient_ratio_editor", " in"))
