# Form implementation generated from reading ui file 'nutrient_ratio_widget.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class NutrientRatioWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(687, 50)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_nutrient_name = QtWidgets.QLabel(Form)
        self.lbl_nutrient_name.setObjectName("lbl_nutrient_name")
        self.horizontalLayout.addWidget(self.lbl_nutrient_name)
        self.txt_nutrient_mass = QtWidgets.QLineEdit(Form)
        self.txt_nutrient_mass.setObjectName("txt_nutrient_mass")
        self.horizontalLayout.addWidget(self.txt_nutrient_mass)
        self.cmb_nutrient_mass_unit = QtWidgets.QComboBox(Form)
        self.cmb_nutrient_mass_unit.setObjectName("cmb_nutrient_mass_unit")
        self.horizontalLayout.addWidget(self.cmb_nutrient_mass_unit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txt_ingredient_mass = QtWidgets.QLineEdit(Form)
        self.txt_ingredient_mass.setObjectName("txt_ingredient_mass")
        self.horizontalLayout.addWidget(self.txt_ingredient_mass)
        self.cmb_ingredient_mass_unit = QtWidgets.QComboBox(Form)
        self.cmb_ingredient_mass_unit.setObjectName("cmb_ingredient_mass_unit")
        self.horizontalLayout.addWidget(self.cmb_ingredient_mass_unit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_nutrient_name.setText(_translate("Form", "nutrient_name: "))
        self.label_2.setText(_translate("Form", " in"))
