# Form implementation generated from reading ui file 'user_requirements_editor.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_user_requirements_editor(object):
    def setupUi(self, user_requirements_editor):
        user_requirements_editor.setObjectName("user_requirements_editor")
        user_requirements_editor.resize(615, 482)
        self.verticalLayout = QtWidgets.QVBoxLayout(user_requirements_editor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(user_requirements_editor)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(user_requirements_editor)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView_2 = QtWidgets.QListView(self.groupBox)
        self.listView_2.setObjectName("listView_2")
        self.horizontalLayout.addWidget(self.listView_2)
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget)
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(user_requirements_editor)
        QtCore.QMetaObject.connectSlotsByName(user_requirements_editor)

    def retranslateUi(self, user_requirements_editor):
        _translate = QtCore.QCoreApplication.translate
        user_requirements_editor.setWindowTitle(_translate("user_requirements_editor", "Form"))
        self.label.setText(_translate("user_requirements_editor", "User Requirements"))
        self.groupBox.setTitle(_translate("user_requirements_editor", "Global Flag Requirements"))
        self.pushButton.setText(_translate("user_requirements_editor", "Adopt Flag"))
        self.pushButton_2.setText(_translate("user_requirements_editor", "Remove Flag"))
